#!/usr/bin/env python3
"""
MAD-214 Phase 1A: Export FP8-constrained centroids from a calibration report
into a C header for the kernel + wrapper to #include.

Reads a fit_centroids.py JSON report (per_kv_layer granularity) and emits one
flat C array per (variant, kv, layer) of centroid magnitudes encoded as E4M3
bytes. The kernel uses these as in-register LUT entries: extract N-bit index
from packed block, lookup E4M3 byte, XOR sign bit, multiply by per-block scale
post-WMMA.

Usage:
  python3 export_centroids.py \\
      --report /var/tmp/mad214_fit_scales.json \\
      --output ggml/src/ggml-cuda/aiter-integration/turbo_fp8_centroids.h \\
      --variants turbo3_fp8,turbo4_fp8,turbo5_fp8

The report MUST be from a per_kv_layer (or per_kv_layer_head) granularity run
with FP16-scale variants — global mode lacks per-key centroid logs.
"""

import argparse
import json
import sys
from pathlib import Path


# ---------------------------------------------------------------------------
# E4M3 lattice + byte encoding
# ---------------------------------------------------------------------------

def enumerate_e4m3_positive_with_bytes() -> list[tuple[int, float]]:
    """Returns sorted list of (byte, value) for all finite positive E4M3 codes."""
    pairs: list[tuple[int, float]] = []
    for byte in range(0, 0x80):  # sign bit = 0
        e = (byte >> 3) & 0xF
        m = byte & 0x7
        if e == 15 and m == 7:
            continue  # NaN code (we already excluded these centroids at fit time)
        if e == 0:
            val = (2 ** -6) * (m / 8.0)  # subnormal
        else:
            val = (2 ** (e - 7)) * (1 + m / 8.0)  # normal
        pairs.append((byte, val))
    return sorted(pairs, key=lambda p: p[1])


def value_to_e4m3_byte(v: float, pairs: list[tuple[int, float]]) -> int:
    """Find the E4M3 byte whose value exactly equals v (centroid was snapped at fit time)."""
    best = min(pairs, key=lambda p: abs(p[1] - v))
    if abs(best[1] - v) > 1e-6:
        raise ValueError(
            f"value {v} not found in E4M3 lattice (closest: byte=0x{best[0]:02x} val={best[1]})"
        )
    return best[0]


# ---------------------------------------------------------------------------
# Header emission
# ---------------------------------------------------------------------------

C_HEADER_PROLOGUE = '''\
/*
 * MAD-214: Auto-generated turbo-FP8 centroid LUTs.
 *
 * Source report: {source_report}
 * Model:         {model}
 * Calibration:   block_size={block_size}, granularity={granularity},
 *                hadamard={hadamard}, scale_dtype={scale_dtype}
 * Generated by:  scripts/calibration/export_centroids.py
 *
 * DO NOT EDIT by hand. Re-run export_centroids.py with an updated calibration
 * report to regenerate.
 *
 * Storage layout: each centroid set is N_CENTROIDS uint8_t values, each a
 * positive E4M3 representable byte (sign bit = 0). The runtime dequant path
 * is:  byte = LUT[centroid_index_bits];
 *      fp8_val = sign_bit ? byte | 0x80 : byte;
 *      f32_val = fp8_to_f32(fp8_val) * block_scale_fp32_from_fp16;
 *
 * Layer indices in mt_turbo_fp8_attention_layers[] are the only layers with
 * traditional softmax attention; remaining model layers use DeltaNet (no KV
 * cache, no centroids needed).
 */

#pragma once

#include <stdint.h>
#include <stddef.h>

'''


def emit_array_block(name: str, bytes_arr: list[int]) -> str:
    """Single uint8_t[N] array."""
    items = ", ".join(f"0x{b:02x}" for b in bytes_arr)
    return f"static const uint8_t {name}[{len(bytes_arr)}] = {{ {items} }};\n"


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--report", required=True, help="fit_centroids.py JSON report (per_kv_layer mode)")
    p.add_argument("--output", required=True, help="output C header path")
    p.add_argument(
        "--variants",
        default="turbo3_fp8,turbo4_fp8,turbo5_fp8",
        help="comma-separated variant names to export from the report",
    )
    p.add_argument(
        "--model-tag",
        default=None,
        help="symbol-name suffix to disambiguate per-model exports (default: derived from input dir)",
    )
    args = p.parse_args()

    report = json.loads(Path(args.report).read_text())
    results = report.get("results", {})
    pkv = results.get("per_kv_layer") or results.get("per_kv_layer_head")
    if pkv is None:
        sys.exit(
            "Error: report has no per_kv_layer or per_kv_layer_head results. "
            "Re-run fit_centroids.py with --granularity per_kv_layer."
        )

    pairs = enumerate_e4m3_positive_with_bytes()
    print(f"[export_centroids] E4M3 positive lattice: {len(pairs)} unique values", flush=True)

    variants_wanted = [v.strip() for v in args.variants.split(",")]
    available = {v["name"] for v in pkv["variants"]}
    missing = [v for v in variants_wanted if v not in available]
    if missing:
        sys.exit(f"Error: variants not in report: {missing}. Available: {sorted(available)}")

    # Collect attention layer indices from the first variant's per_key_mse keys.
    sample_v = next(v for v in pkv["variants"] if v["name"] == variants_wanted[0])
    keys = list(sample_v.get("per_key_mse", {}).keys())
    # Keys look like 'k_L3', 'v_L7' — extract unique layer indices
    layer_indices = sorted({int(k.split("_L")[1].split("_")[0]) for k in keys})
    print(f"[export_centroids] Attention layers found: {layer_indices}", flush=True)

    # Get model tag for symbol naming
    model = report.get("model") or report.get("input_dir", "unknown")
    if args.model_tag:
        model_tag = args.model_tag
    else:
        # Derive: take last path component, replace bad chars
        model_tag = Path(report.get("input_dir", "unknown")).name.replace("-", "_").replace(".", "_")

    lines = [
        C_HEADER_PROLOGUE.format(
            source_report=args.report,
            model=model,
            block_size=report.get("block_size", "?"),
            granularity=report.get("granularity_mode", "?"),
            hadamard=report.get("hadamard", "?"),
            scale_dtype="see variant suffix",
        )
    ]

    lines.append(f"#define MT_TURBO_FP8_BLOCK_SIZE {report.get('block_size', 32)}\n")
    lines.append(f"#define MT_TURBO_FP8_N_ATTENTION_LAYERS {len(layer_indices)}\n\n")
    lines.append(f"static const int mt_turbo_fp8_attention_layers_{model_tag}[{len(layer_indices)}] = {{ ")
    lines.append(", ".join(str(L) for L in layer_indices))
    lines.append(" };\n\n")

    # Pull centroids from the report. The per_kv_layer mode stores them in
    # variant['extra']['centroids_constrained'] when include_per_key=False,
    # OR inside the centroid_log dict we kept separately.
    # Since _variant_summary with include_per_key=True drops 'extra', we read
    # centroid_log directly.
    centroid_log = pkv.get("centroid_log", {})
    if not centroid_log:
        sys.exit(
            "Error: report does not contain centroid_log. Re-run fit_centroids.py — "
            "the per_kv_layer branch should populate it."
        )

    for vname in variants_wanted:
        n_centroids = {"turbo3_fp8": 8, "turbo4_fp8": 16, "turbo5_fp8": 32}.get(vname)
        if n_centroids is None:
            sys.exit(f"Error: unknown centroid count for variant {vname}")

        lines.append(
            f"// -----------------------------------------------------------------------\n"
            f"// {vname}: {n_centroids} centroids per (kv, layer)\n"
            f"// -----------------------------------------------------------------------\n"
        )
        lines.append(f"#define MT_{vname.upper()}_N_CENTROIDS {n_centroids}\n\n")

        variant_centroids = centroid_log.get(vname, {})
        if not variant_centroids:
            sys.exit(f"Error: no centroids logged for variant {vname}")

        # Per-(kv, layer) flat arrays
        for kv in ("k", "v"):
            for L in layer_indices:
                key = f"{kv}_L{L}"
                if key not in variant_centroids:
                    sys.exit(f"Error: missing centroids for {vname} key {key}")
                centroid_values = variant_centroids[key]
                # Pad with the smallest centroid byte if E4M3 snap collapsed duplicates
                # (kernel expects exactly N_CENTROIDS entries indexed by N bits)
                if len(centroid_values) < n_centroids:
                    pad_val = centroid_values[0]
                    centroid_values = list(centroid_values) + [pad_val] * (n_centroids - len(centroid_values))
                if len(centroid_values) > n_centroids:
                    centroid_values = centroid_values[:n_centroids]
                bytes_arr = [value_to_e4m3_byte(v, pairs) for v in centroid_values]
                symbol = f"mt_{vname}_centroids_{model_tag}_{kv}_L{L}"
                lines.append(emit_array_block(symbol, bytes_arr))

        # Index table: [kv][layer_pos] → pointer to centroid array.
        # Use layer_pos (0..N_ATTENTION_LAYERS-1) not raw layer index L.
        lines.append(
            f"\nstatic const uint8_t * const mt_{vname}_lut_{model_tag}[2][{len(layer_indices)}] = {{\n"
        )
        for kv in ("k", "v"):
            row = ", ".join(f"mt_{vname}_centroids_{model_tag}_{kv}_L{L}" for L in layer_indices)
            lines.append(f"    /* {kv} */ {{ {row} }},\n")
        lines.append("};\n\n")

    Path(args.output).write_text("".join(lines))
    print(f"[export_centroids] Wrote {args.output} ({sum(len(l) for l in lines):,} bytes)", flush=True)


if __name__ == "__main__":
    main()
