"""KroneckerRotation — Q = H_a ⊗ H_b for ml8 weight quantization.

Production-quality factored rotation for QuaRot-style weight quantization.
H_b is a Sylvester-construction Hadamard matrix (power-of-2 dim, deterministic).
H_a is a small random orthogonal matrix for the non-power-of-2 factor.

For input dim d = a * b, storing the rotation as the (a, b) factored form costs
~a^2 floats instead of d^2; applying it as a Kronecker product costs O(d*(a+log b))
instead of O(d^2). Both savings matter at production inference time.

Schema (stored in ml8 blob's "rotation" field):
    {
        "kind": "kronecker_orth_sylvester",
        "h_a": torch.Tensor(a, a),
        "a_dim": int a,
        "b_dim": int b,
        "in_features": int d = a*b,
        "seed": int,
    }

The forward(x) applies Q to the last dim of x (rotates along input axis of a Linear).
The inverse(x) applies Q^T (equal to Q^-1 since Q is orthogonal).
"""

import math
from typing import Optional

import torch


class KroneckerRotation:
    """Factored orthogonal rotation Q = H_a ⊗ H_b applied to last dim of inputs.

    For input dim d = a * b, reshape x to (..., a, b) and apply
        Y = H_a @ X @ H_b.T
    which equals (H_a ⊗ H_b) · vec(X) under row-major flatten.

    Inverse uses Q^T = H_a^T ⊗ H_b^T, so:
        X = H_a.T @ Y @ H_b

    Storage: only h_a (a×a) needs to be persisted — h_b is the deterministic
    Sylvester Hadamard of size b_dim, regenerated on load.
    """

    def __init__(self, h_a: torch.Tensor, b_dim: int):
        if h_a.dim() != 2 or h_a.shape[0] != h_a.shape[1]:
            raise ValueError(f"h_a must be square 2D, got shape {tuple(h_a.shape)}")
        if b_dim < 1 or (b_dim & (b_dim - 1)) != 0:
            raise ValueError(f"b_dim must be a positive power of 2, got {b_dim}")
        self.h_a = h_a
        self.a_dim = h_a.shape[0]
        self.b_dim = b_dim
        self.d = self.a_dim * b_dim
        self.h_b = sylvester(b_dim).to(dtype=h_a.dtype)

    def _factors_on(self, x: torch.Tensor):
        h_a = self.h_a.to(device=x.device, dtype=x.dtype)
        h_b = self.h_b.to(device=x.device, dtype=x.dtype)
        return h_a, h_b

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """Right-multiply last dim of x by Q = H_a ⊗ H_b (PyTorch row-vector convention).

        Computes x @ Q. Derivation: with X = x.reshape(..., a, b),
            (x @ Q)[k*b + l] = sum_{i,j} X[i,j] H_a[i,k] H_b[j,l]
                              = (H_a.T @ X @ H_b)[k, l].
        """
        if x.shape[-1] != self.d:
            raise ValueError(f"last dim {x.shape[-1]} != d={self.d}")
        h_a, h_b = self._factors_on(x)
        X = x.reshape(*x.shape[:-1], self.a_dim, self.b_dim)
        Y = h_a.T @ X @ h_b
        return Y.reshape(x.shape)

    def inverse(self, x: torch.Tensor) -> torch.Tensor:
        """Right-multiply last dim of x by Q.T (= Q^{-1} since Q is orthogonal).

        Computes x @ Q.T = H_a @ X @ H_b.T.
        """
        if x.shape[-1] != self.d:
            raise ValueError(f"last dim {x.shape[-1]} != d={self.d}")
        h_a, h_b = self._factors_on(x)
        X = x.reshape(*x.shape[:-1], self.a_dim, self.b_dim)
        Y = h_a @ X @ h_b.T
        return Y.reshape(x.shape)

    def to_dict(self) -> dict:
        """Serialize for storage in ml8 blob's 'rotation' field.

        Only h_a needs to be stored — h_b is the deterministic Sylvester of size b_dim,
        regenerated by from_dict. h_a kept on CPU so the blob is device-agnostic.
        """
        return {
            "kind": "kronecker_orth_sylvester",
            "h_a": self.h_a.detach().cpu(),
            "a_dim": self.a_dim,
            "b_dim": self.b_dim,
            "in_features": self.d,
        }

    @classmethod
    def from_dict(cls, blob: dict) -> "KroneckerRotation":
        if blob.get("kind") != "kronecker_orth_sylvester":
            raise ValueError(f"unsupported rotation kind: {blob.get('kind')!r}")
        return cls(h_a=blob["h_a"], b_dim=int(blob["b_dim"]))


def factor_for_dim(d: int, max_b: int = 1024) -> tuple:
    """Pick (a, b) such that a*b == d, b is the largest power of 2 ≤ max_b that divides d.

    max_b defaults to 1024 to match the existing turbo_fp8_hadamard.cuh FWHT kernel's
    upper bound — keeps the factorization compatible with a future production runtime
    that reuses the KV-side kernel for the H_b leg.

    Examples (max_b=1024):
        2560 → (5, 512)
        9216 → (9, 1024)
        4096 → (4, 1024)   # capped at max_b; pure-Sylvester (1, 4096) would exceed kernel
        256  → (1, 256)
        7    → (7, 1)      # no power-of-2 factor, degenerates to pure random orthogonal
    """
    if d < 1:
        raise ValueError(f"d must be positive, got {d}")
    if max_b < 1 or (max_b & (max_b - 1)) != 0:
        raise ValueError(f"max_b must be a positive power of 2, got {max_b}")
    b = 1
    while (b * 2) <= max_b and d % (b * 2) == 0:
        b *= 2
    return d // b, b


def rotate_hessian(H: torch.Tensor, rotation: "KroneckerRotation") -> torch.Tensor:
    """Compute Q.T @ H @ Q using the rotation's Kronecker structure.

    For our row-vector convention:
      rotation.forward(M) = M @ Q   (right-multiply each row by Q)
      M.T @ Q             = rotation.forward(M.T)
      Q.T @ M             = (M.T @ Q).T = rotation.forward(M.T).T

    So Q.T @ H @ Q = rotation.forward( rotation.forward(H).T ).T

    H is (d, d); each rotation.forward call costs O(d * (a + log b)) instead of the
    O(d^3) of a dense Q matmul. For d=2560, a=5, b=512: ~36K ops × d rows ≈ 10^8 vs
    ~10^10 for dense. ~100× speedup, matters when Hessians are big.
    """
    return rotation.forward(rotation.forward(H).T).T


def random_orthogonal(a: int, seed: int) -> torch.Tensor:
    """Random orthogonal matrix of size (a, a), uniformly distributed on O(a).

    Implementation: QR decomposition of a Gaussian random matrix. The sign-fix
    on diag(R) ensures uniform distribution per Mezzadri 2007 (`How to generate
    random matrices from the classical compact groups`); without it the
    distribution is biased.
    """
    g = torch.Generator(device="cpu").manual_seed(int(seed))
    M = torch.randn(a, a, generator=g, dtype=torch.float32)
    Q, R = torch.linalg.qr(M)
    # Mezzadri sign fix: multiply each column of Q by sign of corresponding diag(R)
    d = torch.sign(torch.diagonal(R))
    return Q * d.unsqueeze(0)


def sylvester(n: int) -> torch.Tensor:
    """Sylvester-construction Hadamard matrix of size (n, n), normalized so H @ H.T = I.

    n must be a power of 2. H_1 = [[1]]; H_{2k} = [[H_k, H_k], [H_k, -H_k]] / sqrt(2)
    keeps orthonormality at each doubling.
    """
    if n < 1 or (n & (n - 1)) != 0:
        raise ValueError(f"sylvester(n): n must be a positive power of 2, got {n}")
    H = torch.tensor([[1.0]], dtype=torch.float32)
    while H.shape[0] < n:
        top = torch.cat([H, H], dim=1)
        bot = torch.cat([H, -H], dim=1)
        H = torch.cat([top, bot], dim=0) / math.sqrt(2.0)
    return H
